# Generated by Django 4.1.2 on 2022-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='men', max_length=50),
            preserve_default=False,
        ),
    ]
